import '../imports/startup/accounts-config.js';
import '../imports/startup/routes.js'
// layout
import '../imports/ui/layouts/app_body.js'
// home
import '../imports/ui/home/register_login.js'
import '../imports/ui/home/rooms.js';
import '../imports/ui/home/home.js';
// room
import '../imports/ui/room/chat_box.js';
import '../imports/ui/room/show_room.js';
import '../imports/ui/room/user_invite.js';
// invites
import '../imports/ui/invites/my_invites.js';